/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsPostIdRouteImport } from './routes/posts_.$postId'
import { Route as CustomerTrackingRouteImport } from './routes/customer/tracking'
import { Route as CustomerReviewRouteImport } from './routes/customer/review'
import { Route as CustomerReserveRouteImport } from './routes/customer/reserve'
import { Route as CustomerMenuRouteImport } from './routes/customer/menu'
import { Route as CustomerCartRouteImport } from './routes/customer/cart'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTablesRouteImport } from './routes/admin/tables'
import { Route as AdminReservationsRouteImport } from './routes/admin/reservations'
import { Route as AdminPostsRouteImport } from './routes/admin/posts'
import { Route as AdminPaymentsHistoryRouteImport } from './routes/admin/payments-history'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminMenuManagementRouteImport } from './routes/admin/menu-management'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminKitchenRouteImport } from './routes/admin/kitchen'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'

const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts_/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerTrackingRoute = CustomerTrackingRouteImport.update({
  id: '/customer/tracking',
  path: '/customer/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerReviewRoute = CustomerReviewRouteImport.update({
  id: '/customer/review',
  path: '/customer/review',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerReserveRoute = CustomerReserveRouteImport.update({
  id: '/customer/reserve',
  path: '/customer/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerMenuRoute = CustomerMenuRouteImport.update({
  id: '/customer/menu',
  path: '/customer/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCartRoute = CustomerCartRouteImport.update({
  id: '/customer/cart',
  path: '/customer/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTablesRoute = AdminTablesRouteImport.update({
  id: '/admin/tables',
  path: '/admin/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/admin/reservations',
  path: '/admin/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/admin/posts',
  path: '/admin/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsHistoryRoute = AdminPaymentsHistoryRouteImport.update({
  id: '/admin/payments-history',
  path: '/admin/payments-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMenuManagementRoute = AdminMenuManagementRouteImport.update({
  id: '/admin/menu-management',
  path: '/admin/menu-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKitchenRoute = AdminKitchenRouteImport.update({
  id: '/admin/kitchen',
  path: '/admin/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/menu': typeof MenuRoute
  '/posts': typeof PostsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu-management': typeof AdminMenuManagementRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payments-history': typeof AdminPaymentsHistoryRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/tables': typeof AdminTablesRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/menu': typeof CustomerMenuRoute
  '/customer/reserve': typeof CustomerReserveRoute
  '/customer/review': typeof CustomerReviewRoute
  '/customer/tracking': typeof CustomerTrackingRoute
  '/posts/$postId': typeof PostsPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/menu': typeof MenuRoute
  '/posts': typeof PostsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu-management': typeof AdminMenuManagementRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payments-history': typeof AdminPaymentsHistoryRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/tables': typeof AdminTablesRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/menu': typeof CustomerMenuRoute
  '/customer/reserve': typeof CustomerReserveRoute
  '/customer/review': typeof CustomerReviewRoute
  '/customer/tracking': typeof CustomerTrackingRoute
  '/posts/$postId': typeof PostsPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/menu': typeof MenuRoute
  '/posts': typeof PostsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu-management': typeof AdminMenuManagementRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payments-history': typeof AdminPaymentsHistoryRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/tables': typeof AdminTablesRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/menu': typeof CustomerMenuRoute
  '/customer/reserve': typeof CustomerReserveRoute
  '/customer/review': typeof CustomerReviewRoute
  '/customer/tracking': typeof CustomerTrackingRoute
  '/posts_/$postId': typeof PostsPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/menu'
    | '/posts'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/kitchen'
    | '/admin/login'
    | '/admin/menu-management'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/payments-history'
    | '/admin/posts'
    | '/admin/reservations'
    | '/admin/tables'
    | '/admin/users'
    | '/customer/cart'
    | '/customer/menu'
    | '/customer/reserve'
    | '/customer/review'
    | '/customer/tracking'
    | '/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/menu'
    | '/posts'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/kitchen'
    | '/admin/login'
    | '/admin/menu-management'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/payments-history'
    | '/admin/posts'
    | '/admin/reservations'
    | '/admin/tables'
    | '/admin/users'
    | '/customer/cart'
    | '/customer/menu'
    | '/customer/reserve'
    | '/customer/review'
    | '/customer/tracking'
    | '/posts/$postId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/menu'
    | '/posts'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/kitchen'
    | '/admin/login'
    | '/admin/menu-management'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/payments-history'
    | '/admin/posts'
    | '/admin/reservations'
    | '/admin/tables'
    | '/admin/users'
    | '/customer/cart'
    | '/customer/menu'
    | '/customer/reserve'
    | '/customer/review'
    | '/customer/tracking'
    | '/posts_/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  MenuRoute: typeof MenuRoute
  PostsRoute: typeof PostsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminKitchenRoute: typeof AdminKitchenRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMenuManagementRoute: typeof AdminMenuManagementRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPaymentsHistoryRoute: typeof AdminPaymentsHistoryRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminTablesRoute: typeof AdminTablesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CustomerCartRoute: typeof CustomerCartRoute
  CustomerMenuRoute: typeof CustomerMenuRoute
  CustomerReserveRoute: typeof CustomerReserveRoute
  CustomerReviewRoute: typeof CustomerReviewRoute
  CustomerTrackingRoute: typeof CustomerTrackingRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts_/$postId': {
      id: '/posts_/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/tracking': {
      id: '/customer/tracking'
      path: '/customer/tracking'
      fullPath: '/customer/tracking'
      preLoaderRoute: typeof CustomerTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/review': {
      id: '/customer/review'
      path: '/customer/review'
      fullPath: '/customer/review'
      preLoaderRoute: typeof CustomerReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/reserve': {
      id: '/customer/reserve'
      path: '/customer/reserve'
      fullPath: '/customer/reserve'
      preLoaderRoute: typeof CustomerReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/menu': {
      id: '/customer/menu'
      path: '/customer/menu'
      fullPath: '/customer/menu'
      preLoaderRoute: typeof CustomerMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/cart': {
      id: '/customer/cart'
      path: '/customer/cart'
      fullPath: '/customer/cart'
      preLoaderRoute: typeof CustomerCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tables': {
      id: '/admin/tables'
      path: '/admin/tables'
      fullPath: '/admin/tables'
      preLoaderRoute: typeof AdminTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/admin/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/admin/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments-history': {
      id: '/admin/payments-history'
      path: '/admin/payments-history'
      fullPath: '/admin/payments-history'
      preLoaderRoute: typeof AdminPaymentsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/menu-management': {
      id: '/admin/menu-management'
      path: '/admin/menu-management'
      fullPath: '/admin/menu-management'
      preLoaderRoute: typeof AdminMenuManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kitchen': {
      id: '/admin/kitchen'
      path: '/admin/kitchen'
      fullPath: '/admin/kitchen'
      preLoaderRoute: typeof AdminKitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  MenuRoute: MenuRoute,
  PostsRoute: PostsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminKitchenRoute: AdminKitchenRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMenuManagementRoute: AdminMenuManagementRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPaymentsHistoryRoute: AdminPaymentsHistoryRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminTablesRoute: AdminTablesRoute,
  AdminUsersRoute: AdminUsersRoute,
  CustomerCartRoute: CustomerCartRoute,
  CustomerMenuRoute: CustomerMenuRoute,
  CustomerReserveRoute: CustomerReserveRoute,
  CustomerReviewRoute: CustomerReviewRoute,
  CustomerTrackingRoute: CustomerTrackingRoute,
  PostsPostIdRoute: PostsPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
